services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - AUTH0_DOMAIN=dev-7oe1511t7bkdsevl.eu.auth0.com
      - AUTH0_AUDIENCE=${AUTH0_CLIENT_ID}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/src/data:/app/src/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge